Add idx to DataFrame
elastic/eland pull request #353
Opened 2021-06-07 15:54 UTC by V1NAY8

Work on #352 

- Implemented the pandas similar functionality
- Modified `noxfile.py` similar to `urllib3` because existing one is hanging on windows forever

@sethmlarson  or @stevedodson  Please review :)

2021-06-07 15:54 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2021-07-17 14:29 UTC, sethmlarson commented
Jenkins test this please

2021-07-28 07:14 UTC, V1NAY8 commented
Rebased this, ask jenkins to test this once

2021-07-28 11:36 UTC, sethmlarson commented
jenkins test this please

2021-07-28 11:38 UTC, sethmlarson requested changes
Couple of small comments otherwise this looks good!

2021-07-28 12:31 UTC, sethmlarson approved these changes
LGTM

2021-07-28 12:32 UTC, sethmlarson commented
jenkins test this please

2021-07-28 12:55 UTC, merged