Add support to Pandas 1.3.0 and LightGBM 3.2.1
elastic/eland pull request #362
Opened 2021-07-18 10:34 UTC by V1NAY8

Closes #248 #359 

@sethmlarson / @stevedodson Please review :)

Ask jenkins to test this.

2021-07-18 10:34 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2021-07-18 10:41 UTC, V1NAY8 commented on eland/plotting/_matplotlib/hist.py
> -from pandas.core.dtypes.generic import ABCIndexClass
Pandas renamed `ABCIndexClass` to `ABCIndex`
https://github.com/pandas-dev/pandas/pull/38329

2021-07-18 14:29 UTC, sethmlarson requested changes
If possible we should support pandas 1.2.0 and 1.3.0. I left some suggestions on how we can do this. We should also test against both 1.2.0 and 1.3.0 if possible, might require some changes to our CI?

2021-07-18 14:29 UTC, sethmlarson commented on eland/etl.py
>  from elasticsearch.helpers import parallel_bulk
```python
try:
    from pandas.io.parsers import _c_parser_defaults  # type: ignore
    _DEFAULT_LOW_MEMORY: bool = _c_parser_defaults["low_memory"]
except ImportError:
    _DEFAULT_LOW_MEMORY = True
```

2021-07-18 14:29 UTC, sethmlarson commented on eland/etl.py
> +        "on_bad_lines": on_bad_lines,
If we detect pandas <1.3.0 let's transform `on_bad_lines="warn"` -> `kwargs["warn_bad_lines"]=True` and `on_bad_lines="error"` -> `kwargs["error_bad_lines"] = True`

2021-07-18 14:29 UTC, sethmlarson commented on eland/etl.py
> +    if kwargs["names"] is None and kwargs["prefix"] is None:
Let's only do this on pandas 1.3.0+

2021-07-18 14:29 UTC, sethmlarson commented on eland/plotting/_matplotlib/hist.py
> +from pandas.core.dtypes.generic import ABCIndex
```python
try:
    # pandas<1.3.0
    from pandas.core.dtypes.generic import ABCIndexClass as ABCIndex
except ImportError:
    # pandas>=1.3.0
    from pandas.core.dtypes.generic import ABCIndex
```

2021-07-18 14:29 UTC, sethmlarson commented on requirements-dev.txt
> +lightgbm==3.2.1
This isn't necessary, we already installed 3.x in testing.

We need to update `setup.py` though to change `lightgbm>=2,<2.4` to `lightgbm>=2,<4`

2021-07-19 13:50 UTC, sethmlarson commented
jenkins test this please

2021-07-19 14:17 UTC, sethmlarson commented on noxfile.py
>      session.run("python", "-m", "pip", "uninstall", "--yes", "pandas")
Not sure if we need the `uninstall+install`, what happens if we only keep the `python -m pip install pandas=={pandas_version}`?

2021-07-19 14:17 UTC, sethmlarson commented on eland/common.py
> +PANDAS_VERSION = pd.__version__
We would prefer a tuple of ints for easier/correct comparisons:

`PANDAS_VERSION: Tuple[int, int] = tuple(int(part) for part in pd_version.split(".") if part.isdigit())[:2]`

2021-07-19 14:19 UTC, sethmlarson commented on eland/etl.py
> +        if kwargs["warn_bad_lines"] is True:
Let's separate the `if kwargs["names"] / "prefix" ...` section and the `if kwargs["warn_bad_lines"] / "error_bad_lines"...` section so we can tell they're different.

2021-07-19 14:20 UTC, sethmlarson commented on eland/etl.py
> +    if PANDAS_VERSION < "1.3.0":
This can be an `else` statement.

2021-07-19 14:20 UTC, sethmlarson commented on eland/etl.py
> +    # If names and prefix both passed as None, it's considering them as specified values and throwing ValueError
Move this comment to be closer to the section that's handling it.

2021-07-19 14:22 UTC, sethmlarson commented
jenkins test this please

2021-07-21 17:44 UTC, sethmlarson commented
jenkins test this please

2021-07-21 17:46 UTC, sethmlarson approved these changes
This looks good, only one change for you then I'll merge:

2021-07-21 17:46 UTC, sethmlarson commented on eland/etl.py
> +    if PANDAS_VERSION > (1, 3):
Should be `PANDAS_VERSION >= (1, 3):` to include (1, 3, 0)?

2021-07-26 16:18 UTC, sethmlarson commented
@V1NAY8 Can you rebase this on `master`?

2021-07-26 16:38 UTC, V1NAY8 commented
Ok,
Rebase is done. Lets see what jenkins says
 so some jupyter notebook tests will fail for 1.3.0, You want me to fix them in this PR itself ?

2021-07-26 16:53 UTC, sethmlarson commented
@V1NAY8 Yeah you can fix the notebook tests, thanks!

2021-07-26 18:02 UTC, sethmlarson commented
jenkins test this please

2021-07-27 02:05 UTC, V1NAY8 commented
@sethmlarson Notebook tests are all good. All the tests are passed. Also Pandas doesnt support 3.6.  Only that failed. 

So, remove 3.6?

2021-07-27 16:01 UTC, sethmlarson approved these changes
LGTM

2021-07-27 16:01 UTC, merged