Upgrade torch to 1.13.1 and check the cluster version before uploading a NLP model.
elastic/eland pull request #522
Opened 2023-03-31 14:19 UTC by davidkyle

In the 8.7 release of Elasticsearch PyTorch is upgraded to version 1.13.1 (elastic/ml-cpp#2430). The change means the same version of PyTorch is used when tracing the model in Eland as evaluating it in Elasticsearch.

Some models traced in version 1.13 of PyTorch cannot be evaluated in version 1.9 or earlier. Because of this Eland will now not upload a model to a pre 8.7 Elasticsearch.

The Elasticsearch client requirement is bumped to 8.7 and `transformers` compatibility is updated to include the latest release. PyTorch 1.13 is compatible with Python 3.10, the docs are updated to reflect this.

Closes #481

2023-03-31 14:26 UTC, davidkyle commented
CI is failing because version 8.7 of the elasticsearch python client is not released yet

2023-04-03 13:47 UTC, davidkyle commented
> CI is failing because version 8.7 of the elasticsearch python client is not released yet

I've reverted back to version 8.3. Version 8.7 is recommended but not necessary

2023-05-02 02:11 UTC, JonathanHourany commented
Hello! Just wanted to check in on this branch. I was toying around with eland earlier and found myself in a little bit of a dependency struggle so I'm glad to see the bumps to `torch` and Python 3.10. Any thoughts on when this might get merged to master and release?

2023-05-02 08:19 UTC, davidkyle commented
Hi @JonathanHourany this change will be in the next release: version 8.8. Please watch the PR as I will try to get it merged soon.

If you are using Eland to install models in Elasticsearch but having problems with dependencies I recommend using the Docker image. I tend to use the Docker image to simplify my setup. It is easy to get started, see the instructions in the README: https://github.com/elastic/eland#docker

2023-05-02 18:16 UTC, sethmlarson requested changes
Looks good, I only had two small comments:

2023-05-02 18:16 UTC, sethmlarson commented on requirements-dev.txt
>  # Elasticsearch uses v1.11.0 of PyTorch
Update this comment (maybe with a reference to the ml-cpp PR?)

2023-05-02 18:16 UTC, sethmlarson commented on tests/ml/pytorch/test_pytorch_model_upload_pytest.py
>          reason="This test requires at least Elasticsearch version 8.0.0",
Update `reason` field

2023-05-02 20:36 UTC, sethmlarson approved these changes

2023-05-03 14:18 UTC, joshdevins approved these changes
LGTM. I only did a visual pass, I didn't run anything.

2023-05-03 17:11 UTC, JonathanHourany commented
> Hi @JonathanHourany this change will be in the next release: version 8.8. Please watch the PR as I will try to get it merged soon.

That's great to hear @davidkyle , thanks for the update!

2023-05-19 15:29 UTC, merged