Fix missing method str.removeprefix in Python 3.8
elastic/eland pull request #695
Opened 2024-05-21 09:42 UTC by bartbroere

Eland still supports Python 3.8, so str.removeprefix can be called and raise an `AttributeError`.

Once Eland drops Python 3.8 support this if/else can be removed (only keeping the code in the if).

2024-05-21 13:18 UTC, pquentin requested changes
Thanks! I don't think this is worth a condition, I would use the slice and mention this can be replaced by removeprefix when we remove Python 3.8.

2024-05-21 20:54 UTC, bartbroere commented
> I would use the slice and mention this can be replaced by removeprefix when we remove Python 3.8.

That sounds a bit less verbose indeed. I committed the suggestion.

2024-05-22 04:29 UTC, pquentin approved these changes

2024-05-22 04:30 UTC, pquentin commented
buildkite test this please

2024-05-23 06:12 UTC, pquentin commented
buildkite test this please

2024-05-23 16:49 UTC, pquentin commented
buildkite test this please

2024-05-24 06:25 UTC, merged